name: "PR Checks"
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        name: Action Test
        steps:
            - uses: actions/checkout@v1
            - uses: ./
              with:
                key: ${{ secrets.TB_KEY }}
                secret: ${{ secrets.TB_SECRET }}
                tunnelIdentifier: github-action-tunnel

            - name: "Install Dependencies"
              run: npm install

            - name: "Run Test"
              run: npm run test
              env:
                TB_KEY: ${{ secrets.TB_KEY }}
                TB_SECRET: ${{ secrets.TB_SECRET }}